version: "3.0"

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - bookmark_network
    volumes:
      - redis_data:/data

  bookmark_service:
    container_name: bookmark_service
    image: bookmark_service:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - bookmark_network

networks:
  bookmark_network:
    driver: bridge
    name: bookmark_network

volumes:
  redis_data:
